services:
  - type: web
    name: privacy-checker
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: KIMI_API_KEY
        value: sk-MDciUodKCiEMRfAyhOmQSHmy4Pj0cdmzr9ZRoaRYmqSe1938
